### ISSUE TITLE
Stattstaaten, die auf der Karte fehlen

### ISSUE THREAD

**Issue by webemich** [Kruemi/TROS#36]
Folgende Stadtstaaten fehlen auf der Karte und ich weiss nicht warum:

- Luzern
- Basel
- Mülhausen
- Buron

Habe heute verifiziert, dass es nichts mit dem sql Update zu tun hat (sie fehlten auch auf Master, mag mich doch nicht erinnern, dass sie früher fehlgeschlagen wären)

@Kruemi hast du eine Idee dazu?

**Comment by Kruemi** [comment]
Was mir bis jetzt aufgefallen ist:

Luzern (CS2 Bandar Brunei, CS24 Yerevan), Basel (CS1 Amsterdam, CS23 Vilnius) und Mülhausen (CS19 Seoul, CS25 Zanzibar) sind in 'TROSGeneral_Civilization.sql' doppelt aufgeführt, aber die Definition von Yerevan, Vilnus und Zanzibar wurde auskommentiert. Im WorldBuilder jedoch wurden diese 3 Stadtstaaten als Yerewan, Vilnius und Sansibar platziert. Ich habe dann die anderen Definitionen auskommentiert und das Spiel mit Yerewan, Vilnius und Sansibar gestartet, aber die Städte sind immernoch verschwunden.

Buron (Valletta), Basel (Vilnus), Luzern (Yerevan), Mülhausen (Zanzibar) sind die letzten 4 Städte in 'TROSGeneral_Civilization.sql'. Es scheint also immerhin einen Zusammenhang zu geben.

Auf dem Feld auf dem die Städte stehen sollten sieht man noch die Strassen.

Aber mehr fand ich bis jetzt noch nicht.

**Comment by Kruemi** [comment]
@webemich wenn wir unsere Stadtstaaten selber kreieren (d.h. nicht nur die bestehenden Civ-Stadtstaaten bearbeiten), kann man dann die Städte im WorldBuilder einfach durch unsere ersetzen?

**Comment by webemich** [comment]
Das könnte funktionieren. Ich hatte bloss zu Beginn einen eigenen Stadtstaat nicht zum laufen gebracht. Deshalb dachte ich es sei einfacher bestehende umzubenennen.

(Weil auf der Karte ursprünglich bestimmte Stadtstaaten geladen wurden, und einzelne nicht (wie immer im Spiel) musste ich diese einzeln anfügen. Deshalb waren die ursprünglich geplanten auskommentiert und fehlende angefügt.)

Hinweis: Genf kann unverändert aus dem Spiel übernommen werden.

**Comment by Kruemi** [comment]
Das Problem konnte behoben werden.
In 'TROS_Scenario_Config.sql' unter 'MapSizes' war die Anzahl Stadtstaaten auf 18 limitiert. Ist jetzt auf 22 erhöht worden.
