### ISSUE TITLE
gitignore schlägt bei .civ6suo fehl

### ISSUE THREAD

**Issue by webemich** [Kruemi/TROS#37]
Git versucht immer .civ6ssuo Dateien zu synchronisieren, obwohl .civ6suo der .gitignore Datei hinzugefügt worden ist.

@Kruemi weisst du warum?

**Comment by Kruemi** [comment]
Hatte mich auch schon darüber gewundert. Hab es jetzt herausgefunden: falls eine Datei bereits commited wurde bevor sie zu .gitignore hinzugefügt wurde, wird sie immer noch getracked. Man muss also das Tracking für diese Datei separat deaktivieren (git rm --cached filename). Ich habe das Tracking im direkt master angepasst.

@webemich wenn es mit dem neuen master bei dir jetzt auch richtig funktioniert, kannst du diesen Issue schliessen

**Comment by webemich** [comment]
Danke für den Hinweis!

Das funktioniert jetzt bei mir.
